---
# tasks file for haproxy

- yum:
        name:
                - haproxy
                - firewalld
        state: present
- template:
        src: haproxy.cfg.j2
        dest: /etc/haproxy/haproxy.cfg
  notify: restart service
- service:
        name: "{{ item }}"
        state: started
        enabled: true
  loop:
          - haproxy
          - firewalld
- firewalld:
        service: http
        immediate: yes
        permanent: true
        state: enabled
